# This workflow will rebuild the emodpy Docs triggered when changes to rst, python or requirements.txt files are intended.

name: Rebuild emodpy Docs
on:
  push:
    paths: 
      - '**.py'
      - '**/*docs/**'
      - '**/requirements.txt'
  pull_request:
    paths:
      - '**.py'
      - '**/*docs/**'
      - '**/requirements.txt'   

jobs:
  emodpy-docs-rebuild:

    runs-on: ubuntu-latest
    steps:
    - name: Repo Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.branch }}

    # Python Setup
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
          python-version: 3.9 

    # emodpy setup:
    - name: Install emodpy requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt --index-url=https://packages.idmod.org/api/pypi/pypi-production/simple
    - name: Install the emodpy package
      run: |
        pip install -e . --index-url=https://packages.idmod.org/api/pypi/pypi-production/simple

    # docs setup and build:
    - name: Install documentation build requirements
      run: |
        pip install -r docs/requirements.txt --index-url=https://packages.idmod.org/api/pypi/pypi-production/simple
    - name: Build docs - html - no break
      working-directory: 'docs'
      run: |
        make clean
        make htmlnobreak

