name: "Rebuild docs"

on:
  push:
    branches:
      # only run this on
      - master
    paths:
      - '**.py'
      - 'docs/**'
      - 'setup.py'
      - 'requirements.txt'

jobs:
  rebuild-documentation:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'Bump version: ')"
    steps:
      - uses: actions/checkout@v2
        with:
          path: 'emodpy'
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('emodpy/docs/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        working-directory: 'emodpy/docs'
        run: |
          python -m pip install --upgrade pip py-make
          pip install -r requirements.txt
          pip install backoff
      - name: Install emodpy
        working-directory: 'emodpy'
        run: |
          pip install -e . --index-url=https://packages.idmod.org/api/pypi/pypi-production/simple
      - name: Build docs
        working-directory: 'emodpy/docs'
        run: |
          make html
      - uses: actions/checkout@v2
        with:
          ref: 'gh-pages'
          path: 'gh-pages'
      - name: Copy docs
        run: |
          cp -r emodpy/docs/_build/html/* gh-pages/
          ls -al gh-pages/
      - name: Commit docs
        working-directory: 'gh-pages'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add --all .
          git commit -m "${{ github.event.head_commit.message }}"
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${{ secrets.DOCS_DEPLOY_KEY }}"
          git push
