name: Build docs

on:
  push:
    paths: 
      - '**.py'
      - '**/*docs/**'

  pull_request:
    paths:
      - '**.py'
      - '**/*docs/**'

jobs:
  emodpy-docs-rebuild:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[docs] --extra-index-url=https://packages.idmod.org/api/pypi/pypi-production/simple
      - name: Build docs - html - no break
        working-directory: 'docs'
        run: |
          make clean
          make htmlnobreak
