# This workflow will rebuild the emodpy Docs triggered when changes to rst, python or requirements.txt files are intended.

name: Rebuild emodpy Docs
on:
  push:
    paths: 
      - '**.py'
      - '**/*docs/**'

  pull_request:
    paths:
      - '**.py'
      - '**/*docs/**'

jobs:
  emodpy-docs-rebuild:

    runs-on: ubuntu-latest
    steps:
    - name: Repo Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.branch }}

    # Python Setup
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
          python-version: 3.9 

    # emodpy setup:
    - name: Install the emodpy package
      run: |
        python -m pip install --upgrade pip
        pip install -e . --extra-index-url=https://packages.idmod.org/api/pypi/pypi-production/simple

    # docs setup and build:
    - name: Install documentation build requirements
      run: |
        pip install -r docs/requirements.txt --extra-index-url=https://packages.idmod.org/api/pypi/pypi-production/simple

    - name: Build docs - html - no break
      working-directory: 'docs'
      run: |
        make clean
        make htmlnobreak

