# This workflows will upload a Python Package using Twine when a release is created

name: "Staging: emodpy"

on:
  push:
    branches:
      # only run this on
      - 'main'
      - 'release**'
    paths:
      - 'emodpy/**'
      - "pyproject.toml"

jobs:
  deploy-emodpy-staging:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'Bump version: ')"
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('.dev_scripts/build-requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install -r ./.dev_scripts/build-requirements.txt
          git config --global user.name "IDM Tools"
          git config --global user.email "idmtools@idmod.org"

      - uses: actions/checkout@v4

      - name: Bump version
        run: |
          bump2version patch --commit

      - name: Build and publish
        env:
          TWINE_REPOSITORY_URL: https://packages.idmod.org/api/pypi/idm-pypi-staging/
          TWINE_USERNAME: ${{ secrets.PYPI_STAGING_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_STAGING_PASSWORD }}
        run: |
          pip install build
          python -m build --wheel
          git push
          twine upload dist/*
