name: Test and deploy to staging

permissions:
  contents: write # Allow writing to the repository (e.g., commits, pushes)

on:
  push:
    branches:
      - main
    paths:
      - 'emodpy/**'
      - "pyproject.toml"

jobs:
  run-pr-tests:
    name: Run unit and container tests
    uses: ./.github/workflows/run-pr-tests.yml

  run-comps-tests:
    name: Run COMPS tests
    uses: ./.github/workflows/run-comps-tests.yml
    secrets:
      COMPS_USER: ${{ secrets.COMPS_USER }}
      COMPS_PASSWORD: ${{ secrets.COMPS_PASSWORD }}

  staging-build-package:
    name: Push to staging
    needs: [run-pr-tests, run-comps-tests]
    uses: ./.github/workflows/staging-build-package.yml
    secrets:
      STAGING_ARTIFACTORY_USERNAME: ${{ secrets.STAGING_ARTIFACTORY_USERNAME }}
      STAGING_ARTIFACTORY_PASSWORD: ${{ secrets.STAGING_ARTIFACTORY_PASSWORD }}
